### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by atsay714** [TehGM/PoE-QualityRecipesCalculator#3]
`Failed calculating vendor recipes: Arithmetic operation resulted in an overflow.`

Seems when dealing with too many flasks, it overflows. I'm guessing it's because it brute forces all the permutations. Might I humbly suggestion this: 

https://www.geeksforgeeks.org/bin-packing-problem-minimize-number-of-used-bins/

**Comment by TehGM** [comment]
Fixed in 2b0a3ac (Release 1.0.2).
